apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "sealed-secrets-encrypted-file-example.fullname" . }}
  annotations:
    # this is because the name is a deployment time parameter
    # consider also using "cluster-wide" if the namespace is also a parameter
    # please make sure you understand the implications, see README
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app.kubernetes.io/name: {{ include "sealed-secrets-encrypted-file-example.name" . }}
    helm.sh/chart: {{ include "sealed-secrets-encrypted-file-example.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sealed-secrets-encrypted-file-example.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
  encryptedData:
    foo: {{ .Values.foo }}
    foo2: {{ .Values.foo2 }}

